language: python
python:
  - "3.6"
cache: apt
addons:
before_install:
install:
  # Build/test dependencies
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  # Get fab to test fab
  - pip install -e .
# Command to run tests
script:
  - pytest --cov=pycalib pycalib
after_success:
  - coveralls
